image:
  file: .gitpod.dockerfile

tasks:
  - name: Setup Environment
    command: |
      if [ -d ".vscode/extensions" ] && [ "$(ls -A .vscode/extensions/*.vsix 2>/dev/null)" ]; then
        for file in .vscode/extensions/*.vsix; do
          code --install-extension "$file" || true
        done
      else
        echo "No .vsix extensions found to install."
      fi

      if [ -f requirements.txt ]; then
        pip install -r requirements.txt
      else
        echo "requirements.txt not found, skipping pip install."
      fi

vscode:
  extensions:
    - ms-python.debugpy
    - PKief.material-icon-theme
    - charliermarsh.ruff
    - ms-python.python
    - esbenp.prettier-vscode
    - christian-kohler.path-intellisense
    - yzhang.markdown-all-in-one
    - GitHub.github-vscode-theme
